# Assertion : if this exception is thrown, the involved code that produced it is sure to have a bug.
#0 : Wrong index returned by findColumn.
#1 : Field name that caused the wrong calculation. 
assert.wrong_index_for_column_name=[Erreur interne de l''API] L''index de colonne {0}, illégal, a été renvoyé par findColumn pour le champ ''{1}''.

# Exception : field is not a date. 
#0 : Field name.
#1 : SQL Query.
#2 : Field value that is not a date.
excp.field_is_not_a_date=Le champ {0} dans la requête ''{1}'' a une valeur ''{2}'' qui n''est pas une date.  

# Exception : field is not numeric. 
#0 : Field name.
#1 : Field type.
#2 : SQL Query.
#3 : Field value that is not a number.
excp.field_is_not_numeric=Le champ {0} de type {1} dans la requête ''{2}'' a une valeur ''{3}'' qui n''est pas numérique. 

# Exception : the result set has no more results.
#0: SQL Query that was attempted but failed.
#1: Database name.
excp.no_more_results=Le ResultSet n''a plus de résultats pour la requête SQL ''{0}'' sur la base de données {1}.

# Log : a string value has been converted with a charset.
#0 : Field name.
#1 : Field value after being converted with the charset.
#2 : Charset used.
log.string_field_charset=Les octets du champ de nom ''{0}'' ont été converties en ''{1}'' en utilisant le jeu de caractères {2}.
